---
container:
  image: debian:bullseye

task:
  install_script: |
    apt-get update
    apt-get install -y libfile-next-perl

  test_script: |
    ./scrub "$PWD"
    awk '/LICENSE/ {print $1, "", $3}' < ".scrub-$(date +%F)" | shasum -c -
